In [6]:
from scipy import stats
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [10]:
df = pd.read_csv('tugasPD1.csv')
df

          Nim  nilai tugas  nilai quiz  nilai uts  nilai uas
0    180001.0         72.0        96.0       95.0       99.0
1    180002.0         75.0        87.0       78.0       76.0
2    180003.0         99.0        74.0       80.0       85.0
3    180004.0         71.0        88.0       99.0       92.0
4    180005.0         77.0        96.0       99.0       95.0
5    180006.0         95.0        81.0       95.0       98.0
6    180007.0         89.0        86.0       79.0       90.0
7    180008.0         90.0       100.0       89.0       87.0
8    180009.0         91.0        91.0       92.0       81.0
9    180010.0         77.0        82.0       83.0       80.0
10   180011.0         90.0        85.0       72.0       71.0
11   180012.0         91.0        95.0       98.0      100.0
12   180013.0         93.0        91.0       97.0       98.0
13   180014.0         89.0        82.0       82.0       95.0
14   180015.0         95.0        73.0       77.0       82.0
15   180016.0         78.0        82.0       96.0       85.0
16   180017.0         79.0        94.0       86.0       70.0
17   180018.0         77.0        80.0       99.0       76.0
18   180019.0         75.0       100.0       96.0       79.0
19   180020.0         95.0        73.0       84.0      100.0
20   180021.0         73.0        86.0       82.0       70.0
21   180022.0         83.0        87.0       80.0       81.0
22   180023.0         91.0       100.0       91.0       90.0
23   180024.0         98.0        90.0       76.0       91.0
24   180025.0         95.0        92.0       83.0       85.0
25   180026.0         70.0        84.0       83.0       91.0
26   180027.0         92.0        75.0       91.0       95.0
27   180028.0         76.0        96.0       74.0       89.0
28   180029.0         93.0        99.0       99.0       92.0
29   180030.0         93.0       100.0       74.0       91.0
..        ...          ...         ...        ...        ...
73   180074.0         74.0        83.0      100.0       92.0
74   180075.0         92.0        75.0       93.0       83.0
75   180076.0         73.0        80.0       97.0       83.0
76   180077.0         92.0        79.0       91.0       76.0
77   180078.0         86.0        72.0       97.0       88.0
78   180079.0         72.0        92.0       92.0       85.0
79   180080.0         74.0        83.0       85.0       96.0
80   180081.0         96.0        94.0       97.0       97.0
81   180082.0         87.0        77.0       73.0       88.0
82   180083.0         88.0        95.0       71.0       89.0
83   180084.0         92.0        91.0       75.0       72.0
84   180085.0         90.0        71.0       74.0       77.0
85   180086.0         94.0        70.0       96.0       91.0
86   180087.0         75.0        98.0       89.0       91.0
87   180088.0         74.0        96.0       98.0       87.0
88   180089.0         97.0        99.0       98.0       82.0
89   180090.0         89.0        73.0       86.0       94.0
90   180091.0         93.0        90.0       95.0       74.0
91   180092.0         79.0        80.0       84.0       75.0
92   180093.0        100.0        98.0       72.0       89.0
93   180094.0         79.0        78.0       89.0       80.0
94   180095.0         98.0        91.0       72.0       99.0
95   180096.0         96.0        76.0       90.0       92.0
96   180097.0         92.0        76.0       72.0       83.0
97   180098.0         89.0        86.0       73.0       85.0
98   180099.0         73.0        90.0       85.0       88.0
99   180100.0         83.0        79.0       89.0       97.0
100       NaN          NaN         NaN        NaN        NaN
101       NaN          NaN         NaN        NaN        NaN
102       NaN          NaN         NaN        NaN        NaN

[103 rows x 5 columns]

In [19]:
from IPython.display import HTML, display
import tabulate
table=[
    ["method"]+[x for x in df.columns],
    ["describe()"]+['<pre>'+str(df[col].describe())+'</pre>' for col in df.columns],
    ["count()"]+[df[col].count() for col in df.columns],
    ["mean()"]+[df[col].mean() for col in df.columns],
    ["std()"]+["{:.2f}".format(df[col].std()) for col in df.columns],
    ["min()"]+[df[col].min() for col in df.columns],
    ["max()"]+[df[col].max() for col in df.columns],
    ["q1()"]+[df[col].quantile(0.25) for col in df.columns],
    ["q2()"]+[df[col].quantile(0.50) for col in df.columns],
    ["q3()"]+[df[col].quantile(0.75) for col in df.columns],
    ["skew()"]+["{:.2f}".format(df[col].skew()) for col in df.columns],
]

display(HTML(tabulate.tabulate(table, tablefmt='html')))